name: 'Wait Netlify Deployment with API Token'
description: 'Wait for Netlify to complete live site or preview deploy'
branding:
  icon: 'clock'
  color: 'blue'
env:
  NETLIFY_TOKEN: 'Netlify personal access token'
inputs:
  site_id:
    description: 'The Netlify site API id'
    required: true
  max_timeout:
    description: 'The max time to run the action'
    required: false
outputs:
  url:
    description: 'The fully qualified deploy URL'
runs:
  using: 'node16'
  main: 'index.js'
